# Generated by Django 4.0 on 2021-12-13 16:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('Name', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True, max_length=200)),
                ('Update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='guild',
            fields=[
                ('guild', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('Nickname', models.CharField(max_length=200, unique=True)),
                ('Characters_number', models.IntegerField(default=0)),
                ('Timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Update', models.DateTimeField(auto_now=True)),
                ('Identity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.guild')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Start_time', models.DateTimeField(auto_now_add=True, help_text='Start date')),
                ('End_time', models.DateTimeField(verbose_name='End time')),
                ('Product_Name', models.CharField(max_length=200)),
                ('Price', models.IntegerField()),
                ('Count', models.IntegerField()),
                ('PS', models.TextField(blank=True, null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('state', models.CharField(max_length=200, primary_key=True, serialize=False, unique=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Axe',
            fields=[
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.character')),
                ('Inner', models.IntegerField(default=0, help_text='斧製造內圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal1', models.IntegerField(default=0, help_text='戰斧製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal2', models.IntegerField(default=0, help_text='巨斧大劍製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal3', models.IntegerField(default=0, help_text='戰戟製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact1', models.IntegerField(default=0, help_text='召喚神斧製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact2', models.IntegerField(default=0, help_text='赤炎鐮刀製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact3', models.IntegerField(default=0, help_text='熊爪神斧制造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact4', models.IntegerField(default=0, help_text='裂域斧製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crossbow',
            fields=[
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.character')),
                ('Inner', models.IntegerField(default=0, help_text='十字弓製造內圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal1', models.IntegerField(default=0, help_text='十字弓製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal2', models.IntegerField(default=0, help_text='重型十字弓製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal3', models.IntegerField(default=0, help_text='輕便十字弓製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact1', models.IntegerField(default=0, help_text='愁淵連弩製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact2', models.IntegerField(default=0, help_text='霹靂連弩製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact3', models.IntegerField(default=0, help_text='圍城弩制造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact4', models.IntegerField(default=0, help_text='朔能炮製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gloves',
            fields=[
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.character')),
                ('Inner', models.IntegerField(default=0, help_text='戰鬥手套製造內圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal1', models.IntegerField(default=0, help_text='格鬥手套製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal2', models.IntegerField(default=0, help_text='戰鬥護碗製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal3', models.IntegerField(default=0, help_text='尖刺護手製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact1', models.IntegerField(default=0, help_text='烏鴉之爪製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact2', models.IntegerField(default=0, help_text='煉獄火之手製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact3', models.IntegerField(default=0, help_text='熊爪士之擊制造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact4', models.IntegerField(default=0, help_text='阿瓦隆之拳製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mace',
            fields=[
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.character')),
                ('Inner', models.IntegerField(default=0, help_text='錘杖製造內圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal1', models.IntegerField(default=0, help_text='錘杖製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal2', models.IntegerField(default=0, help_text='重型錘杖製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal3', models.IntegerField(default=0, help_text='晨星製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact1', models.IntegerField(default=0, help_text='基石錘杖製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact2', models.IntegerField(default=0, help_text='夢魘錘杖製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact3', models.IntegerField(default=0, help_text='卡姆蘭錘杖制造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact4', models.IntegerField(default=0, help_text='守誓雙錘製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plate_armor',
            fields=[
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.character')),
                ('Inner', models.IntegerField(default=0, help_text='盔甲製造內圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal1', models.IntegerField(default=0, help_text='士兵盔甲製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal2', models.IntegerField(default=0, help_text='騎士盔甲製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal3', models.IntegerField(default=0, help_text='守衛盔甲製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact1', models.IntegerField(default=0, help_text='守墓人盔甲製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact2', models.IntegerField(default=0, help_text='惡魔盔甲製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact3', models.IntegerField(default=0, help_text='審判盔甲制造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact4', models.IntegerField(default=0, help_text='英勇盔甲製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plate_helmet',
            fields=[
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.character')),
                ('Inner', models.IntegerField(default=0, help_text='頭盔製造內圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal1', models.IntegerField(default=0, help_text='士兵頭盔製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal2', models.IntegerField(default=0, help_text='騎士頭盔製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal3', models.IntegerField(default=0, help_text='守衛頭盔製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact1', models.IntegerField(default=0, help_text='守墓人頭盔製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact2', models.IntegerField(default=0, help_text='惡魔頭盔製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact3', models.IntegerField(default=0, help_text='審判頭盔制造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact4', models.IntegerField(default=0, help_text='英勇頭盔製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plate_shoes',
            fields=[
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.character')),
                ('Inner', models.IntegerField(default=0, help_text='鐵甲鞋製造內圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal1', models.IntegerField(default=0, help_text='士兵鞋製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal2', models.IntegerField(default=0, help_text='騎士鞋製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal3', models.IntegerField(default=0, help_text='守衛鞋製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact1', models.IntegerField(default=0, help_text='守墓人之靴製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact2', models.IntegerField(default=0, help_text='惡魔之靴製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact3', models.IntegerField(default=0, help_text='審判長靴制造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact4', models.IntegerField(default=0, help_text='英勇之靴製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shield',
            fields=[
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.character')),
                ('Inner', models.IntegerField(default=0, help_text='盾牌製造內圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal1', models.IntegerField(default=0, help_text='盾牌製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal2', models.IntegerField(default=0, help_text='石棺之膚製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal3', models.IntegerField(default=0, help_text='怯懦之盾製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact1', models.IntegerField(default=0, help_text='破面之盾製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact2', models.IntegerField(default=0, help_text='星域神盾製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sword',
            fields=[
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.character')),
                ('Inner', models.IntegerField(default=0, help_text='劍製造內圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal1', models.IntegerField(default=0, help_text='闊劍製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal2', models.IntegerField(default=0, help_text='闊刃大劍製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal3', models.IntegerField(default=0, help_text='雙劍製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact1', models.IntegerField(default=0, help_text='王者之劍製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact2', models.IntegerField(default=0, help_text='斷水劍製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact3', models.IntegerField(default=0, help_text='雙刀制造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('artifact4', models.IntegerField(default=0, help_text='傭王闊刃大劍製造外圈', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('Timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provider_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PS', models.TextField(blank=True, null=True)),
                ('Timestamp', models.DateTimeField(auto_now_add=True, null=True)),
                ('Update', models.DateTimeField(auto_now=True)),
                ('Order_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.order')),
                ('Provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='State',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.state'),
        ),
        migrations.AddField(
            model_name='order',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
        migrations.AddField(
            model_name='character',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
    ]
