# Generated by Django 4.0 on 2021-12-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='Nickname',
            field=models.CharField(default='預設', max_length=200, unique=True),
        ),
    ]
