# Generated by Django 4.0 on 2021-12-14 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_alter_member_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='axe',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.character'),
        ),
        migrations.AlterField(
            model_name='crossbow',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.character'),
        ),
        migrations.AlterField(
            model_name='gloves',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.character'),
        ),
        migrations.AlterField(
            model_name='mace',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.character'),
        ),
        migrations.AlterField(
            model_name='plate_armor',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.character'),
        ),
        migrations.AlterField(
            model_name='plate_helmet',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.character'),
        ),
        migrations.AlterField(
            model_name='plate_shoes',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.character'),
        ),
        migrations.AlterField(
            model_name='shield',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.character'),
        ),
        migrations.AlterField(
            model_name='sword',
            name='Name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='member.character'),
        ),
    ]
